// Building a combat: the combatants from the party and the encounter's roster (or from where everyone stands in the
// world), initiative, the stats block and the opening log. addCombatant lets a late arrival join a running fight.
import { getAuthoredCharacter } from '../character/authoredCharacters.js'
import { createMissionResources } from '../rules/missionResources.js'
import { normalizeCondition } from '../rules/personalCondition.js'
import { seededRandomInt } from '../rules/seededRandom.js'
import { toBattleMap } from './battleMap.js'
import { addLog, turnHeader } from './combatLog.js'
import { facingToward, getCombatantList, isActive } from './combatSelectors.js'
import { canTakeCover } from './coverSystem.js'
import { DEFAULT_ENCOUNTER_ID, getEncounter } from './encounters.js'
import { buildInitiativeOrder } from './initiativeSystem.js'
import { tileDistance } from './rangeSystem.js'
import { freshTurn } from './turnActions.js'
import { getCharacterWeapons, withStandardIssue } from './weaponSystem.js'

// condition / facing: carried in from the world when combat starts where everyone already stands. condition: the
// character's personal condition (rules/personalCondition.js: Stress, Injuries, Defeated); the same object shape the
// world keeps, handed back when the fight ends.
// guard: null, or { byId, round } while a Guard is up on this combatant (until the start of its next turn).
// id: the actor's id (a world NPC's id when combat starts in the world; otherwise the character's own id). The character
// keeps its own id: one character, whichever actor or combatant uses it.
function createCombatant(character, { id = character.id, side, controller, position, condition = null, facing = null }) {
  const weapons = getCharacterWeapons(character)
  return {
    id,
    character,
    side,
    controller,
    position,
    condition: normalizeCondition(condition),
    inCover: false,
    guard: null,
    facing,
    weaponIds: weapons.map((weapon) => weapon.id),
  }
}

// The roster (authored character ids, adaptation/characters.json) fills the map's enemy spawns in order; a map with fewer
// spawns fields fewer enemies.
function createEnemyCharacters(encounter, mapFile) {
  return encounter.roster.slice(0, mapFile.markers.enemySpawns.length).map((characterId, index) => ({
    character: getAuthoredCharacter(characterId),
    position: mapFile.markers.enemySpawns[index],
  }))
}

// Running totals for diagnosing and (later) batch-simulating combat. Counts events, not UI.
function createStats(combatants) {
  return {
    attacks: 0,
    attacksHit: 0,
    // Momentum: points generated by party tasks, saved to the pool, lost over the maximum, and spent (by use).
    momentum: { generated: 0, saved: 0, lost: 0, spentDice: 0, spentDirect: 0, spentReroll: 0, spentExtraActions: 0, spentSeverity: 0, spentCancelThreat: 0, spentCounterattack: 0 },
    // Threat: points added (by source) and removed.
    threat: { fromDeadly: 0, fromNpcMomentum: 0, fromDice: 0, spentByNpcs: 0, cancelled: 0 },
    // Actions other than attacking: how often each was taken, and how many of their tasks passed.
    tasks: { guard: 0, firstAid: 0, scan: 0, persuade: 0, intimidate: 0, direct: 0, interact: 0, extraMinor: 0, secondMajor: 0, counterattack: 0, passed: 0 },
    // Injuries from successful attacks: suffered (by type), avoided, and the Stress taken to avoid them.
    injuries: { suffered: 0, stun: 0, deadly: 0, avoided: 0, stressTaken: 0, threatSpent: 0, stressComplications: 0, fatigued: 0 },
    byCombatant: Object.fromEntries(combatants.map((combatant) => [combatant.id, freshCombatantStats()])),
  }
}
const freshCombatantStats = () => ({ attacks: 0, attacksHit: 0, injuriesInflicted: 0, injuriesSuffered: 0, injuriesAvoided: 0, stressTaken: 0, lastAttackRound: 0 })

// players: RuntimeCharacters controlled by the player, in party order; each stands on the map's player start of the same
// index (members beyond the map's player starts are left out). map: a parsed map file (src/maps/mapFormat.js).
// seed: a whole number; it fixes initiative ties and every roll.
// placements (optional): { players, enemies }, each [{ id?, character, position, condition?, facing? }] (id: the world
// actor's id; defaults to the character's). Used when
// combat starts in the exploration world: everyone fights from where they stand instead of the map's starts and spawns.
// resources: the mission's { momentum, threat } (rules/missionResources.js); a standalone fight starts a fresh pair.
// nominatedLeaders: { player, enemy } leader ids set by a scenario or party (rules/authority.js); null = none.
// sceneTraits: the scene's traits ([{ name, potency }]); combat in the world keeps them in step with the scenario.
export function createCombat({
  encounterId = DEFAULT_ENCOUNTER_ID,
  map: mapFile,
  players,
  seed,
  initiativeOptions,
  placements = null,
  resources = createMissionResources(),
  nominatedLeaders = null,
  sceneTraits = [],
}) {
  const encounter = getEncounter(encounterId)
  const combatSeed = seed >>> 0
  const playerPlacements =
    placements?.players ?? players.slice(0, mapFile.markers.playerStarts.length).map((character, index) => ({ character, position: mapFile.markers.playerStarts[index] }))
  const playerCombatants = playerPlacements.map((placement) =>
    createCombatant(withStandardIssue(placement.character, encounter.standardIssueWeapon), { ...placement, side: 'player', controller: 'player' }),
  )
  const enemyCombatants = (placements?.enemies ?? createEnemyCharacters(encounter, mapFile)).map((placement) =>
    createCombatant(placement.character, { ...placement, side: 'enemy', controller: 'ai' }),
  )
  const map = toBattleMap(mapFile)
  const nearestOpponent = (combatant) =>
    [...playerCombatants, ...enemyCombatants]
      .filter((other) => other.side !== combatant.side)
      .sort((a, b) => tileDistance(combatant.position, a.position) - tileDistance(combatant.position, b.position))[0]
  const all = [...playerCombatants, ...enemyCombatants].map((combatant) => ({
    ...combatant,
    inCover: !combatant.condition.defeated && canTakeCover(map, combatant.position),
    facing: combatant.facing ?? facingToward(combatant.position, nearestOpponent(combatant)?.position ?? combatant.position),
  }))
  const order = buildInitiativeOrder(all, seededRandomInt(combatSeed), { firstSide: 'player', ...initiativeOptions })
  // Someone already down (from an earlier fight) never takes the first turn.
  const turnIndex = Math.max(0, order.findIndex((id) => !all.find((combatant) => combatant.id === id).condition.defeated))
  const first = all.find((combatant) => combatant.id === order[turnIndex])
  return {
    encounterId,
    mapId: mapFile.id,
    weather: mapFile.weather,
    seed: combatSeed,
    rolls: 0,
    map,
    combatants: Object.fromEntries(all.map((combatant) => [combatant.id, combatant])),
    order,
    round: 1,
    turnIndex,
    turn: freshTurn(),
    // Saved turns of the other members of the current party group (see getTurnGroup), keyed by combatant id.
    groupTurns: {},
    // Assists set up this round: { [assisted ally id]: helper id }. Used by the ally's next attack; cleared each round.
    assists: {},
    // The mission's group Momentum and Threat for the length of the fight (handed back when it ends).
    resources,
    nominatedLeaders: { player: null, enemy: null, ...nominatedLeaders },
    sceneTraits,
    // While an ally acts on a Direct: { commanderId, allyId, commanderTurn } (the commander's turn waits meanwhile).
    directed: null,
    // Allies already directed this round (one Direct each per round).
    directedThisRound: [],
    // Enemies the party has scanned this fight ({ [id]: true }; combatScan.js).
    scanned: {},
    // Major actions each combatant has taken this round ({ [id]: count }; MAX_MAJORS_PER_ROUND).
    majorsThisRound: {},
    // Combatants whose turn has started this round (a Guard on them ends when their next turn starts).
    startedThisRound: [first.id],
    // An Injury waiting for the player's Avoid Injury decision: { targetId, attackerId, injury, option } (see injuryStep).
    incomingInjury: null,
    // A party member who just became Fatigued and must choose the attribute to shut down: { combatantId }.
    pendingFatigue: null,
    // A party defender who won an opposed attack and may Counterattack: { defenderId, attackerId, weaponId, injuryModes,
    // cost } (combatCounterattack.js).
    pendingCounterattack: null,
    // Notable NPCs that have spent Threat to Avoid Injury this scene (Book p.291: once per scene).
    avoidedThisScene: [],
    // Communication conditions for Direct (rules/communication.js): { remoteBlocked, reason }. null = nothing blocks comms.
    comms: null,
    // null until the party ambushes or is spotted first (see canAmbush); then { ambusherId, targetId, success } or { passed: true }.
    ambush: null,
    pending: null,
    result: null,
    outcome: null,
    aiReason: null,
    lastDecision: null,
    lastMove: null,
    lastAction: null,
    // Set only for combat started in the exploration world (src/exploration/combatLink.js):
    // knowledge: { [enemyId]: { [playerId]: { known, lastKnownPosition, source } } } - an enemy with an entry only treats
    // the party members it knows about as opponents. blockedKeys: tiles held by NPCs standing outside the fight.
    knowledge: null,
    blockedKeys: [],
    stats: createStats(all),
    log: [
      {
        id: 0,
        round: 1,
        kind: 'info',
        lines: [`Combat begins. Seed ${combatSeed}.`, `Initiative (sides alternate, party first; each side by Daring, then Control): ${order.map((id) => all.find((c) => c.id === id).character.name).join(', ')}`],
      },
      { id: 1, round: 1, kind: 'round', lines: ['ROUND 1'] },
      { id: 2, round: 1, kind: 'turn', lines: turnHeader(first) },
    ],
  }
}

// A late arrival (an enemy that heard or saw the fight): joins from where it stands and takes the last initiative slot,
// so it first acts at the end of the current round. placement: as in createCombat.
export function addCombatant(state, placement, { side = 'enemy', controller = 'ai' } = {}) {
  if (state.combatants[placement.id ?? placement.character.id]) return state
  const combatant = createCombatant(placement.character, { ...placement, side, controller })
  const nearest = getCombatantList(state)
    .filter((other) => other.side !== side && isActive(other))
    .sort((a, b) => tileDistance(combatant.position, a.position) - tileDistance(combatant.position, b.position))[0]
  const joined = {
    ...combatant,
    inCover: canTakeCover(state.map, combatant.position),
    facing: combatant.facing ?? facingToward(combatant.position, nearest?.position ?? combatant.position),
  }
  const stats = structuredClone(state.stats)
  stats.byCombatant[joined.id] = freshCombatantStats()
  return addLog({ ...state, combatants: { ...state.combatants, [joined.id]: joined }, order: [...state.order, joined.id], stats }, [`${joined.character.name} joins the fight.`], 'info')
}
